version: '3.3'

# Establecemos una red personalizada.
networks:
  isolation-network:
    name: isolation-network
    driver: bridge

services:
  chatbot_inove:
    build: .
    # Imágen a utilizar:
    image: inove_chatbot
    container_name: chatbot_inove
    # Utilizamos la red personalizada:
    networks: 
      - isolation-network
    # Le asignamos un "hostname" para realizar las peticiones:
    hostname: chatbot_inove
    ports:
      # Enlazamos el puerto en el que trabaja el BOT
      - "8051:5000"
    expose: 
      - "5000"
    volumes:
      - type: bind
        source: ./model
        target: /opt/bot/model
      